name: mental
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.3.3
  - scipy=1.15.3
  - matplotlib=3.10.8
  - seaborn=0.13.2
  - scikit-learn=1.5.2
  - jupyter=1.1.1
  - joblib=1.5.3
  - threadpoolctl=3.6.0
  - pip
  - pip:
      - plotly==6.5.2
      - kaleido==0.2.1
      - scikit-learn-extra==0.3.0
      - umap-learn==0.5.7
